### PR TITLE
Fix for Issue #493

### PR DESCRIPTION
**Pull request by niklasweimann**
Fix for Issue #493

### CODE REVIEW

**Comment by tleguern** [comment]
Are there any maintainers left on this role? This patch is sorely needed.

**Comment by nre-ableton** [comment]
This PR should also include a change to `meta/main.yml` to add a dependency on the `ansible.utils` collection.

**Comment by nre-ableton** [comment]
Also, ping @bbaassssiiee

**Review by bbaassssiiee — CHANGES_REQUESTED** [review]
Please add dependency on the collection,

**Comment by nre-ableton** [comment]
@bbaassssiiee Thanks for the review. I just wanted to make sure that you'd seen this PR. :+1:

**Comment by nre-ableton** [comment]
@niklasweimann Sorry, I gave you some misleading advice. It seems that roles cannot directly depend on collections (see https://github.com/ansible/ansible/issues/76030#issuecomment-942520399, https://github.com/ansible/ansible/issues/76030#issuecomment-1137238958), and this feature will not be supported by Ansible.

Instead, you'll need to create a `requirements.yml` file. I'd be happy to do this in a new PR and cherry-pick https://github.com/ansible-community/ansible-consul/pull/495/commits/9be85c802a82f95c55f3f238f50cd0dbeaa3b37f and https://github.com/ansible-community/ansible-consul/pull/495/commits/7e592005ce8bd158b0bcbc9ead9c8e5fe0ee11d0 to it.

**Comment by bbaassssiiee** [comment]
Please do

**Comment by nre-ableton** [comment]
See https://github.com/ansible-community/ansible-consul/pull/508

**Pull request merged**
