### PR TITLE
fix support for rhel8/centos8

### PR DESCRIPTION
**Pull request by felixb**

### CODE REVIEW

**Comment by felixb** [comment]
I've addressed the build/lint errors in #425. I'm happy to rebase this one when #425 is merged.

**Comment by bbaassssiiee** [comment]
#425 was a duplicate, #418 was merged instead. So please rebase this PR if you are still interested in contributing.

**Comment by felixb** [comment]
@bbaassssiiee I just rebased my changes to the upstream/mater.

**Comment by bbaassssiiee** [comment]
TODO: centos-6 can be removed.

**Comment by gardar** [comment]
@felixb & @bbaassssiiee 
I'm not sure this change was necessary since [/vars/RedHat.yml](../blob/master/vars/RedHat.yml) already includes different`consul_os_packages` for centos8, centos7, etc.

https://github.com/ansible-community/ansible-consul/blob/819f31dbe9cf35d566c7788416b57c468d5a2528/vars/RedHat.yml#L4-L14

Wouldn't it be cleaner to either add rhel to that list rather than specifying a whole new vars file for RedHat 8 or splitting them all up to vars files (Fedora.yml, OracleLinux.yml, etc ?)

**Pull request merged**
