### PR TITLE
Fix truthiness values in molecule

### PR DESCRIPTION
**Pull request by ppuschmann**

### CODE REVIEW

**Comment by ppuschmann** [comment]
I don't why this is failing https://github.com/ansible-community/ansible-consul/actions/runs/3868407775/jobs/6593825338#step:4:446

**Comment by ppuschmann** [comment]
@bbaassssiiee @brianshumate Could someone please hop in and help fixing the molecule-tests?

I'm not that deep into these tests and I don't know what and why it is breaking here (and apparently all other runs).

**Comment by bbaassssiiee** [comment]
The issues seem container related, and not specific to molecule.

**Comment by bbaassssiiee** [comment]
I disabled a few scenarios and enabled newer distros. Debian containers seem broken.

**Comment by nre-ableton** [comment]
@ppuschmann Please rebase your branch, as we've just made some changes to CI in this repository. I'll have a look at this PR afterwards.

**Comment by bbaassssiiee** [comment]
I created another PR with the same intent, to replace this one.

**Pull request closed without merging**
