### PR TITLE
fix for consul startup script

### PR DESCRIPTION
**Pull request by ck3mp3r**
Consul startup script needs host name/ip for consul cli to function properly, at least for cases where ip is bound to different network device i.e. eth1 etc.

### CODE REVIEW

**Review by brianshumate — COMMENTED** [review]
This is a useful change, thanks! Should it be conditionally templated to also account for use of `consul_ports.https` when it is preferred instead and `consul_ports.http` is disabled though?

**Comment by bbaassssiiee** [comment]
molecule was updated with breaking changes. Fixed.

**Review by bbaassssiiee — APPROVED** [review]
Please rebase your branch and push to trigger a new build.

**Comment by ck3mp3r** [comment]
Hi, wasn't even aware this is still relevant :) 
Nice to see there is still appetite for this change.
We've moved on from this mix of tech in the meantime, but if you feel this will be beneficial please feel free to still merge this PR.

Cheers,
Christian

**Pull request closed without merging**
