### PR TITLE
Dnsmasq improvements

### PR DESCRIPTION
**Pull request by gardar**
Merged a few tasks and disable systemd-resolved if needed.

### CODE REVIEW

**Comment by lanefu** [comment]
@gardar 

do you mind rebasing / resolving conflicts?

**Comment by lanefu** [comment]
@gardar  FYI you can also catch me in irc libera.chat under the same name

**Comment by gardar** [comment]
> @gardar FYI you can also catch me in irc libera.chat under the same name

Gotcha! I'm there too under the same name as on here.

**Comment by IamTheFij** [comment]
FYI. This breaks master in a few ways. There are a couple outstanding PRs to resolve the issue already. I'm not sure who best to review though.

**Comment by gardar** [comment]
@IamTheFij do you mind explaining what breaks?
I tested the changes before creating the PR and it passes the molecule tests.

**Comment by IamTheFij** [comment]
It's explained here: https://github.com/ansible-community/ansible-consul/issues/469

I was personally impacted by `link_source` typo and the `item.when` issue.

**Comment by IamTheFij** [comment]
I imagine the tests don't cover these cases though. Kinda hard to be 100% sure with something like Ansible when configurations differ wildly from system to system.

**Pull request merged**
