### PR TITLE
Fix error when creating gossip key

### PR DESCRIPTION
**Pull request by xterr**
Receiving permission denied when outputting consul keygen into tmp file

### CODE REVIEW

**Comment by nre-ableton** [comment]
Your change looks fine, but I'd like to figure out what's happening with CI before merging this change. Sorry for the delay!

**Comment by nre-ableton** [comment]
CI is now fixed, can you please rebase and fix the conflicts?

**Comment by bastienwirtz** [comment]
Hello there, 

+1, I would be glad to see this one merged, thanks for your PR @xterr! The rebase should be seemless.

**Review by nre-ableton — APPROVED** [review]

**Comment by nre-ableton** [comment]
Everything is passing now, so let's go ahead and merge this. Thanks! 👍

**Pull request merged**
