### PR TITLE
Made cluster bootable

### PR DESCRIPTION
**Pull request by Rodjers**
Removed start_join from bootstrap template. Removed own node from
start_join in server template. Added ui flag and fixed ui_dir in both
server and bootstrap template files.

Added service task to site.yml to start the consul service on all nodes
after finishing provisioning Consul.

Fixed CentOS.yml and Debian.yml to follow Ansible best practices.

### CODE REVIEW

**Comment by Rodjers** [comment]
I have tested this using the preinstall script and vagrant up. It works for both Debian and CentOS. For CentOS i used the box image "centos/7".

**Comment by brianshumate** [comment]
This is great, thank you!

**Comment by Rodjers** [comment]
My pleasure. I should be thanking you. This role was just what i needed.

2016-02-07 22:36 GMT+01:00 Brian Shumate notifications@github.com:

> Merged #3 https://github.com/brianshumate/ansible-consul/pull/3.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/brianshumate/ansible-consul/pull/3#event-542327013.

## 

Mvh
Oddgeir Gitlestad

**Comment by brianshumate** [comment]
:+1:  Glad that you found it useful!

**Pull request merged**
