### PR TITLE
Adding support for Rocky Linux

### PR DESCRIPTION
**Pull request by valdemaras-pipiras**

### CODE REVIEW

**Comment by gardar** [comment]
@valdemaras-pipiras can you please add a molecule scenario for Rocky too?

**Comment by lanefu** [comment]
@valdemaras-pipiras  please rebase and resolve conflcits

**Comment by elcomtik** [comment]
LGTM, would it be possible to merge it?

**Review by bbaassssiiee — APPROVED** [review]

**Review by bbaassssiiee — CHANGES_REQUESTED** [review]
please fix conflicts

**Comment by pugnacity** [comment]
any chance to merge this PR in the near future?

**Comment by bbaassssiiee** [comment]
I cannot rebase the PR due to conflicts.

**Comment by valdemaras-pipiras** [comment]
@bbaassssiiee I'm a bit confused, could you tell me what needs to be fixed?

**Comment by bbaassssiiee** [comment]
I squashed your commits.

**Pull request merged**
