### PR TITLE
Fix: fixed handlers to listen to proper notifiers

### PR DESCRIPTION
**Pull request by xterr**
Fix case for handlers

### CODE REVIEW

**Review by nre-ableton — DISMISSED** [review]
Thanks! :+1:

**Comment by nre-ableton** [comment]
I'm not sure why this PR is failing CI, I will rebase it (I can't tell from GitHub's UI whether it's based on the latest master).

**Comment by xterr** [comment]
I saw it as well. I checked the error messages from the pipeline but I didn’t saw anything relevant to this specific change.

As a suggestion, maybe you can create a new patch version as well? 

I really appreciate your time for fixing this. Thank you

**Comment by nre-ableton** [comment]
There are other issues with CI, I'll try to sort them out this week.

**Comment by nre-ableton** [comment]
CI failures have been resolved in https://github.com/ansible-community/ansible-consul/pull/547. I'll rebase your branch and re-test.

**Comment by nre-ableton** [comment]
Ok, looks good! Thanks for your contribution. 👍

**Review by nre-ableton — APPROVED** [review]
Ok, looks good! Thanks for your contribution. 👍

**Pull request merged**
