### PR TITLE
Allow consul to bind to privileged ports under SELinux enabled configs

### PR DESCRIPTION
**Pull request by mattburgess**

### CODE REVIEW

**Comment by bbaassssiiee** [comment]
Shelll equivalent:  `setcap cap_net_bind_service=+ep /usr/local/bin/consul`

Maybe add a test for kerne versionl 2.6.24+?

**Comment by bbaassssiiee** [comment]
I guess Brian's comment in [this issue for Vault](https://github.com/brianshumate/ansible-vault/issues/107) explains why this PR is not being merged:

**Comment by brianshumate** [comment]
#348 adds `CAP_NET_BIND_SERVICE` to the systemd unit file which I think should be sufficient also?

**Comment by bbaassssiiee** [comment]
> #348 adds `CAP_NET_BIND_SERVICE` to the systemd unit file which I think should be sufficient also?

And also a lot safer. Closing this PR.

**Pull request closed without merging**
