### PR TITLE
add consul health check scripts, working on RHEL 7

### PR DESCRIPTION
**Pull request by TheLastChosenOne**
but should work on other Linux Distributions too
add support for OracleLinux which is basically a RedHat/CentOS

### CODE REVIEW

**Review by bbaassssiiee — DISMISSED** [review]
Please rebase to resolve the conflicts in your branch.

**Comment by TheLastChosenOne** [comment]
Hope it's ok now - created this branch over a year ago.

**Review by lanefu — COMMENTED** [review]
I don't think health checks configuration is appropriate for this role.   That's an implementation detail that should be up to the end-user in another playbook or role.

**Comment by lanefu** [comment]
@TheLastChosenOne 

Your efforts are very much appreciated.   Unfortunately this change is a bad fit for the role.  (see https://github.com/ansible-community/ansible-consul/pull/183#pullrequestreview-384712596).

**Pull request closed without merging**
